global:
  scrape_interval: 15s     # Com qual frequência coletar métricas
  evaluation_interval: 15s # Com qual frequência avaliar regras de alerta

# Configurações de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Regras de alertas (carregadas no início)
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# Configurações de scraping (coleta de métricas)
scrape_configs:
  # Monitoramento do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Monitoramento do Node Exporter (métricas do sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Aplicação Java (descomente e ajuste conforme necessário)
  - job_name: 'java-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Para acessar app no host